package eu.darkbot.ter.dks.api.hangar;

public enum LocalizationID {

    AMMO_A_BL("ammunition_laser_a-bl"),
    AMMO_LCB_10("ammunition_laser_lcb-10"),
    AMMO_MCB_25("ammunition_laser_mcb-25"),
    AMMO_MCB_50("ammunition_laser_mcb-50"),
    AMMO_PIB_100("ammunition_laser_pib-100"),
    AMMO_RSB_75("ammunition_laser_rsb-75"),
    AMMO_SAB_50("ammunition_laser_sab-50"),
    AMMO_UCB_100("ammunition_laser_ucb-100"),

    CPU_ADVANCED_JUMP_CPU_1("equipment_extra_cpu_ajp-01"),
    CPU_AMMUNITION_BUY_CPU_1("equipment_extra_cpu_alb-x"),
    CPU_AUTO_ROCKET_CPU_1("equipment_extra_cpu_arol-x"),
    CPU_CARGO_COMPRESSOR("equipment_extra_cpu_g3x-crgo-x"),
    CPU_CLOAK_CPU_1("equipment_extra_cpu_cl04k-m"),
    CPU_CLOAK_CPU_XL("equipment_extra_cpu_cl04k-xl"),
    CPU_DRONE_CPU_2("equipment_extra_cpu_dr-02"),
    CPU_FUEL_BUY_ASSISTANT("equipment_extra_cpu_fb-x"),
    CPU_HELLSTORM_AUTO_CPU_1("equipment_extra_cpu_rllb-x"),
    CPU_REPAIR_BOT_AUTO_CPU("equipment_extra_cpu_nc-rrb-x"),
    CPU_ROCKET_BUY_CPU_1("equipment_extra_cpu_rb-x"),
    CPU_ROCKET_TURBO_1("equipment_extra_cpu_rok-t01"),
    CPU_SLOT_CPU_4("equipment_extra_cpu_sle-04"),

    DRONE_DESIGN_DEMON("drone_designs_demon"),
    DRONE_DESIGN_HAVOC("drone_designs_havoc"),
    DRONE_DESIGN_HERCULES("drone_designs_hercules"),
    DRONE_DESIGN_HERMES("drone_designs_hermes"),
    DRONE_DESIGN_SPARTAN("drone_designs_spartan"),
    DRONE_FORMATION_TURTLE("drone_formation_f-01-tu"),
    DRONE_FORMATION_ARROW("drone_formation_f-02-ar"),
    DRONE_FORMATION_MOTH("drone_formation_f-09-mo"),
    DRONE_FLAX("drone_flax"),
    DRONE_IRIS("drone_iris"),
    DRONE_APIS("drone_apis"),
    DRONE_ZEUS("drone_zeus"),

    EXTRA_REPAIR_ROBOT_3("equipment_extra_repbot_rep-3"),
    EXTRA_REPAIR_ROBOT_4("equipment_extra_repbot_rep-4"),

    FIREWORKS_09L("ammunition_firework_fwx-l"),
    FIREWORKS_09M("ammunition_firework_fwx-m"),
    FIREWORKS_09S("ammunition_firework_fwx-s"),

    LASER_LF4_HYPERPLASMOID("equipment_weapon_laser_lf-4-hp"),
    LASER_LF3("equipment_weapon_laser_lf-3"),
    LASER_LF4("equipment_weapon_laser_lf-4"),
    LASER_LF4_MAGMADRILL("equipment_weapon_laser_lf-4-md"),
    LASER_LF4_PARITYDRILL("equipment_weapon_laser_lf-4-pd"),
    LASER_LF4_UNSTABLE("equipment_weapon_laser_lf-4-unstable"),

    MINE_ACM_1("ammunition_mine_acm-01"),
    MINE_DD_M01("ammunition_mine_ddm-01"),
    MINE_EMP_M01("ammunition_mine_empm-01"),
    MINE_IM_01("ammunition_mine_im-01"),
    MINE_SAB_M01("ammunition_mine_sabm-01"),

    MODULE_DEFLECTOR("module_defm-1"),
    MODULE_EXPERIENCE_BOOSTER("module_xpm-1"),
    MODULE_LOW_RANGE_LASER_TURRET("module_ltm-lr"),
    MODULE_HONOR_BOOSTER("module_honm-1"),

    ORE_PALLADIUM("resource_ore_palladium"),
    ORE_SEPROM("resource_ore_seprom"),
    ORE_XENOMIT("resource_ore_xenomit"),

    PET10("pet_pet10"),
    PETGEAR_G_AL1("equipment_petgear_g-al1"),
    PETGEAR_G_AR1("equipment_petgear_g-ar1"),
    PETGEAR_G_EL1("equipment_petgear_g-el1"),
    PETGEAR_G_KK1("equipment_petgear_g-kk1"),
    PETGEAR_G_REP1("equipment_petgear_g-rep1"),

    RESOURCE_BLUEPRINT_APIS_PART("resource_blueprint_apis-part"),
    RESOURCE_BLUEPRINT_ZEUS_PART("resource_blueprint_zeus-part"),

    RESOURCE_COLLECTABLE_INDOCTRINEOIL("resource_collectable_indoctrineoil"),
    RESOURCE_COLLECTABLE_AURUS("resource_collectable_aurus"),
    RESOURCE_COLLECTABLE_AXION_BEAM_REGULATOR("resource_collectable_axion-beam-regulator"),
    RESOURCE_COLLECTABLE_BIFENON("resource_collectable_bifenon"),
    RESOURCE_COLLECTABLE_BLACKLIGHT_SHARD("resource_collectable_blacklight-shard"),
    RESOURCE_COLLECTABLE_BOLTRUM("resource_collectable_boltrum"),
    RESOURCE_COLLECTABLE_DARKSILVER_COIN("resource_collectable_darksilver-coin"),
    RESOURCE_COLLECTABLE_DIAMETRION("resource_collectable_diametrion"),
    RESOURCE_COLLECTABLE_ETERNAL_FRAGMENT("resource_collectable_eternal-fragment"),
    RESOURCE_COLLECTABLE_HYDRA_ALLOY("resource_collectable_hydra-alloy"),
    RESOURCE_COLLECTABLE_KYHALON("resource_collectable_kyhalon"),
    RESOURCE_COLLECTABLE_MUCOSUM("resource_collectable_mucosum"),
    RESOURCE_COLLECTABLE_NEPTUNE_ALLOY("resource_collectable_neptune-alloy"),
    RESOURCE_COLLECTABLE_PERMIT("resource_collectable_permit"),
    RESOURCE_COLLECTABLE_POLYCHROMIUM("resource_collectable_polychromium"),
    RESOURCE_COLLECTABLE_PRISMATIUM("resource_collectable_prismatium"),
    RESOURCE_COLLECTABLE_QUICKCOUPON("resource_collectable_quickcoupon"),
    RESOURCE_COLLECTABLE_RINUSK("resource_collectable_rinusk"),
    RESOURCE_COLLECTABLE_SCHISM("resource_collectable_schism"),
    RESOURCE_COLLECTABLE_SCRAPIUM("resource_collectable_scrapium"),
    RESOURCE_COLLECTABLE_SOLIDUS("resource_collectable_solidus"),
    RESOURCE_COLLECTABLE_TETRATHRIN("resource_collectable_tetrathrin"),
    RESOURCE_COLLECTABLE_TRISKELION_ALLOY("resource_collectable_triskelion-alloy"),

    RESOURCE_HIGH_FREQUENCY_CABLE("resource_high-frequency-cable"),
    RESOURCE_HYBRID_PROCESSOR("resource_hybrid-processor"),
    RESOURCE_MICRO_TRANSISTORS("resource_micro-transistors"),
    RESOURCE_NANO_CASE("resource_nano-case"),
    RESOURCE_NANO_CONDENSER("resource_nano-condenser"),
    RESOURCE_PRISMATIC_SOCKET("resource_prismatic-socket"),

    ROCKET_ARRAY_MODULE_LOW_ACCURACY("module_ram-la"),
    ROCKET_ECO_10("ammunition_rocketlauncher_eco-10"),
    ROCKET_HSTRM_01("ammunition_rocketlauncher_hstrm-01"),
    ROCKET_LAUNCHER_HST_2("equipment_weapon_rocketlauncher_hst-2"),
    ROCKET_PLT_2021("ammunition_rocket_plt-2021"),
    ROCKET_PLT_2026("ammunition_rocket_plt-2026"),
    ROCKET_PLT_3030("ammunition_rocket_plt-3030"),
    ROCKET_R_310("ammunition_rocket_r-310"),
    ROCKET_SAR_02("ammunition_rocketlauncher_sar-02"),
    ROCKET_UBR_100("ammunition_rocketlauncher_ubr-100"),

    SHIELD_GENERATOR_SG3N_A03("equipment_generator_shield_sg3n-a03"),
    SHIELD_GENERATOR_SG3N_B01("equipment_generator_shield_sg3n-b01"),
    SHIELD_GENERATOR_SG3N_B02("equipment_generator_shield_sg3n-b02"),
    SHIELD_GENERATOR_SG3N_B03("equipment_generator_shield_sg3n-b03"),
    SPEED_GENERATOR_G3N_6900("equipment_generator_speed_g3n-6900"),
    SPEED_GENERATOR_G3N_7900("equipment_generator_speed_g3n-7900"),

    SHIP_AEGIS("ship_aegis"),
    SHIP_CITADEL_ELITE("ship_c-elite"),
    SHIP_GOLIATH("ship_goliath"),
    SHIP_VENGEANCE_AVENGER("ship_v-avenger"),
    SHIP_GOLIATH_EXALTED("ship_g-exalted"),
    SHIP_VENGEANCE_ADEPT("ship_v-adept"),
    SHIP_SOLACE("ship_solace"),
    SHIP_GOLIATH_ENFORCER("ship_g-enforcer"),
    SHIP_VENGEANCE_CORSAIR("ship_v-corsair"),
    SHIP_VENGEANCE_LIGHTNING("ship_v-lightning"),
    SHIP_VENOM("ship_venom"),
    SHIP_GOLIATH_BASTION("ship_g-bastion"),
    SHIP_VENGEANCE_REVENGE("ship_v-revenge"),
    SHIP_GOLIATH_VETERAN("ship_g-veteran"),
    SHIP_CITADEL("ship_citadel"),
    SHIP_VENGEANCE("ship_vengeance"),
    SHIP_AEGIS_ELITE("ship_a-elite"),
    SHIP_SPECTRUM("ship_spectrum"),
    SHIP_GOLIATH_DESIGN_CRIMSON("ship_goliath_design_crimson"),
    SHIP_GOLIATH_DESIGN_AMBER("ship_goliath_design_amber"),
    SHIP_GOLIATH_DESIGN_JADE("ship_goliath_design_jade"),
    SHIP_GOLIATH_DESIGN_SAPHIRE("ship_goliath_design_sapphire"),

    SPECIAL_AMMO_EMP_01("ammunition_specialammo_emp-01"),
    SPECIAL_AMMO_PLD_8("ammunition_specialammo_pld-8"),
    SPECIAL_AMMO_WIZARD("ammunition_specialammo_wiz-x");

    private final String localizationID;
    private LocalizationID(String id) {
        this.localizationID = id;
    }

    public String getLocalizationID() {
        return this.localizationID;
    }
}
