package eu.darkbot.ter.dks.api.hangar;

public enum LocalizationID {

    AMMO_A_BL("ammunition_laser_a-bl"),
    AMMO_LCB_10("ammunition_laser_lcb-10"),
    AMMO_MCB_25("ammunition_laser_mcb-25"),
    AMMO_MCB_50("ammunition_laser_mcb-50"),
    AMMO_PIB_100("ammunition_laser_pib-100"),
    AMMO_RSB_75("ammunition_laser_rsb-75"),
    AMMO_SAB_50("ammunition_laser_sab-50"),
    AMMO_UCB_100("ammunition_laser_ucb-100"),
    AI_CR1("equipment_aiprotocol_ai-cr1"),
    AI_R1("equipment_aiprotocol_ai-r1"),
    AMMO_EMAA_20("ammunition_laser_emaa-20"),
    AMMO_IDB_125("ammunition_laser_idb-125"),
    AMMO_JOB_100("ammunition_laser_job-100"),
    AMMO_SPACE_CUP_GROUP_C("ammunition_laser_spacecup_group-c"),
    AMMO_SPACE_CUP_GROUP_D("ammunition_laser_spacecup_group-d"),

    CPU_ADVANCED_JUMP_CPU_1("equipment_extra_cpu_ajp-01"),
    CPU_AMMUNITION_BUY_CPU_1("equipment_extra_cpu_alb-x"),
    CPU_AUTO_ROCKET_CPU_1("equipment_extra_cpu_arol-x"),
    CPU_CARGO_COMPRESSOR("equipment_extra_cpu_g3x-crgo-x"),
    CPU_CLOAK_CPU_1("equipment_extra_cpu_cl04k-m"),
    CPU_CLOAK_CPU_XL("equipment_extra_cpu_cl04k-xl"),
    CPU_DRONE_CPU_2("equipment_extra_cpu_dr-02"),
    CPU_FUEL_BUY_ASSISTANT("equipment_extra_cpu_fb-x"),
    CPU_HELLSTORM_AUTO_CPU_1("equipment_extra_cpu_rllb-x"),
    CPU_REPAIR_BOT_AUTO_CPU("equipment_extra_cpu_nc-rrb-x"),
    CPU_ROCKET_BUY_CPU_1("equipment_extra_cpu_rb-x"),
    CPU_ROCKET_TURBO_1("equipment_extra_cpu_rok-t01"),
    CPU_SLOT_CPU_4("equipment_extra_cpu_sle-04"),
    CPU_AIM_CPU_2("equipment_extra_cpu_aim-02"),
    CPU_INSTASHIELD_CPU_1("equipment_extra_cpu_ish-01"),
    CPU_JUMP_CPU_2("equipment_extra_cpu_jp-02"),
    CPU_LABORATORY_CPU_1("equipment_extra_cpu_nc-awb-x"),
    CPU_MINES_TURBO_CPU_2("equipment_extra_cpu_min-t02"),
    CPU_RADAR_CPU("equipment_extra_cpu_rd-x"),
    CPU_SLOT_CPU_2("equipment_extra_cpu_sle-02"),
    CPU_SLOT_CPU_3("equipment_extra_cpu_sle-03"),
    CPU_SMARTBOMB_CPU_1("equipment_extra_cpu_smb-01"),

    DRONE_DESIGN_DEMON("drone_designs_demon"),
    DRONE_DESIGN_HAVOC("drone_designs_havoc"),
    DRONE_DESIGN_HERCULES("drone_designs_hercules"),
    DRONE_DESIGN_HERMES("drone_designs_hermes"),
    DRONE_DESIGN_SPARTAN("drone_designs_spartan"),

    DRONE_DESIGN_BLAZE_ENIGMA("drone_designs_enigma-red"),
    DRONE_DESIGN_BLAZE_PHANTOM("drone_designs_phantom-red"),
    DRONE_DESIGN_BOREALIS_ENIGMA("drone_designs_enigma-green"),
    DRONE_DESIGN_BOREALIS_PHANTOM("drone_designs_phantom-green"),
    DRONE_DESIGN_SANDSTORM_ENIGMA("drone_designs_enigma-orange"),
    DRONE_DESIGN_SANDSTORM_PHANTOM("drone_designs_phantom-orange"),

    DRONE_FORMATION_TURTLE("drone_formation_f-01-tu"),
    DRONE_FORMATION_ARROW("drone_formation_f-02-ar"),
    DRONE_FORMATION_MOTH("drone_formation_f-09-mo"),
    DRONE_FORMATION_HEART("drone_formation_f-11-he"),
    DRONE_FORMATION_DRILL("drone_formation_f-3d-dr"),
    DRONE_FORMATION_VETERAN("drone_formation_f-3d-vt"),
    DRONE_FORMATION_WHEEL("drone_formation_f-3d-wl"),
    DRONE_FORMATION_X("drone_formation_f-3d-x"),

    DRONE_FLAX("drone_flax"),
    DRONE_IRIS("drone_iris"),
    DRONE_APIS("drone_apis"),
    DRONE_ZEUS("drone_zeus"),

    EXTRA_REPAIR_ROBOT_3("equipment_extra_repbot_rep-3"),
    EXTRA_REPAIR_ROBOT_4("equipment_extra_repbot_rep-4"),

    FIREWORKS_09L("ammunition_firework_fwx-l"),
    FIREWORKS_09M("ammunition_firework_fwx-m"),
    FIREWORKS_09S("ammunition_firework_fwx-s"),

    LASER_LF4_HYPERPLASMOID("equipment_weapon_laser_lf-4-hp"),
    LASER_LF3("equipment_weapon_laser_lf-3"),
    LASER_LF4("equipment_weapon_laser_lf-4"),
    LASER_LF4_MAGMADRILL("equipment_weapon_laser_lf-4-md"),
    LASER_LF4_PARITYDRILL("equipment_weapon_laser_lf-4-pd"),
    LASER_LF4_UNSTABLE("equipment_weapon_laser_lf-4-unstable"),
    LASER_PROMETHEUS("equipment_weapon_laser_pr-l"),

    MINE_ACM_1("ammunition_mine_acm-01"),
    MINE_DD_M01("ammunition_mine_ddm-01"),
    MINE_EMP_M01("ammunition_mine_empm-01"),
    MINE_IM_01("ammunition_mine_im-01"),
    MINE_SAB_M01("ammunition_mine_sabm-01"),
    MINE_SL_M01("ammunition_mine_slm-01"),

    MODULE_DEFLECTOR("module_defm-1"),
    MODULE_EXPERIENCE_BOOSTER("module_xpm-1"),
    MODULE_LOW_RANGE_LASER_TURRET("module_ltm-lr"),
    MODULE_HONOR_BOOSTER("module_honm-1"),
    MODULE_HIGH_RANGE_LASER_TURRET("module_ltm-hr"),
    MODULE_MID_RANGE_LASER_TURRET("module_ltm-mr"),
    MODULE_DAMAGE_BOOSTER("module_dmgm-1"),
    MODULE_MID_ACCURACY_ROCKET_ARRAY("module_ram-ma"),

    ORE_PALLADIUM("resource_ore_palladium"),
    ORE_SEPROM("resource_ore_seprom"),
    ORE_XENOMIT("resource_ore_xenomit"),

    PET10("pet_pet10"),
    PETGEAR_AUTOLOOTER("equipment_petgear_g-al1"),
    PETGEAR_AUTORESOURCE_COLLECTOR("equipment_petgear_g-ar1"),
    PETGEAR_ENEMY_LOCATOR("equipment_petgear_g-el1"),
    PETGEAR_KAMIKAZE("equipment_petgear_g-kk1"),
    PETGEAR_PET_REPAIRER("equipment_petgear_g-rep1"),
    PETGEAR_COMBO_SHIP_REPAIR("equipment_petgear_csr-02"),

    PET_DESIGN_BLAZE_MIRAGE("pet_designs_mirage-red"),
    PET_DESIGN_BOREALIS_CHIMERA("pet_designs_chimera-green"),
    PET_DESIGN_BOREALIS_MIRAGE("pet_designs_mirage-green"),
    PET_DESIGN_CHIMERA_BLAZE("pet_designs_chimera-red"),
    PET_DESIGN_SANDSTORM_CHIMERA("pet_designs_chimera-orange"),
    PET_DESIGN_SANDSTORM_MIRAGE("pet_designs_mirage-orange"),

    RESOURCE_BLUEPRINT_APIS_PART("resource_blueprint_apis-part"),
    RESOURCE_BLUEPRINT_ZEUS_PART("resource_blueprint_zeus-part"),

    RESOURCE_COLLECTABLE_INDOCTRINEOIL("resource_collectable_indoctrineoil"),
    RESOURCE_COLLECTABLE_AURUS("resource_collectable_aurus"),
    RESOURCE_COLLECTABLE_AXION_BEAM_REGULATOR("resource_collectable_axion-beam-regulator"),
    RESOURCE_COLLECTABLE_BIFENON("resource_collectable_bifenon"),
    RESOURCE_COLLECTABLE_BLACKLIGHT_SHARD("resource_collectable_blacklight-shard"),
    RESOURCE_COLLECTABLE_BOLTRUM("resource_collectable_boltrum"),
    RESOURCE_COLLECTABLE_DARKSILVER_COIN("resource_collectable_darksilver-coin"),
    RESOURCE_COLLECTABLE_DIAMETRION("resource_collectable_diametrion"),
    RESOURCE_COLLECTABLE_ETERNAL_FRAGMENT("resource_collectable_eternal-fragment"),
    RESOURCE_COLLECTABLE_HYDRA_ALLOY("resource_collectable_hydra-alloy"),
    RESOURCE_COLLECTABLE_KYHALON("resource_collectable_kyhalon"),
    RESOURCE_COLLECTABLE_MUCOSUM("resource_collectable_mucosum"),
    RESOURCE_COLLECTABLE_NEPTUNE_ALLOY("resource_collectable_neptune-alloy"),
    RESOURCE_COLLECTABLE_PERMIT("resource_collectable_permit"),
    RESOURCE_COLLECTABLE_POLYCHROMIUM("resource_collectable_polychromium"),
    RESOURCE_COLLECTABLE_PRISMATIUM("resource_collectable_prismatium"),
    RESOURCE_COLLECTABLE_QUICKCOUPON("resource_collectable_quickcoupon"),
    RESOURCE_COLLECTABLE_RINUSK("resource_collectable_rinusk"),
    RESOURCE_COLLECTABLE_SCHISM("resource_collectable_schism"),
    RESOURCE_COLLECTABLE_SCRAPIUM("resource_collectable_scrapium"),
    RESOURCE_COLLECTABLE_SOLIDUS("resource_collectable_solidus"),
    RESOURCE_COLLECTABLE_TETRATHRIN("resource_collectable_tetrathrin"),
    RESOURCE_COLLECTABLE_TRISKELION_ALLOY("resource_collectable_triskelion-alloy"),
    RESOURCE_COLLECTABLE_HYBRID_ALLOY("resource_collectable_hybrid-alloy"),
    RESOURCE_COLLECTABLE_AGATE_SPLINTER("resource_collectable_agate-splinter"),
    RESOURCE_COLLECTABLE_ASTRALITE("resource_collectable_astralite"),
    RESOURCE_COLLECTABLE_BLACKLIGHT_TRACE("resource_collectable_blacklight-trace"),
    RESOURCE_COLLECTABLE_GALAXYGATE_EXCURSION_UNIT("resource_collectable_ggeu"),
    RESOURCE_COLLECTABLE_INDOCTRINE_ACCELERATOR("resource_collectable_indoctrine-accelerator"),
    RESOURCE_COLLECTABLE_ISOCHRONATE("resource_collectable_isochronate"),
    RESOURCE_COLLECTABLE_MINDFIRE_CEREBRUM("resource_collectable_mindfire-cerebrum"),
    RESOURCE_COLLECTABLE_UNSTABLE_SHARD("resource_collectable_unstable-shard"),

    RESOURCE_BOOTY_KEY("resource_booty-key"),
    RESOURCE_BATTLE_PASS_KEY("resource_battle-pass-key"),
    RESOURCE_HIGH_FREQUENCY_CABLE("resource_high-frequency-cable"),
    RESOURCE_HYBRID_PROCESSOR("resource_hybrid-processor"),
    RESOURCE_MICRO_TRANSISTORS("resource_micro-transistors"),
    RESOURCE_NANO_CASE("resource_nano-case"),
    RESOURCE_NANO_CONDENSER("resource_nano-condenser"),
    RESOURCE_PRISMATIC_SOCKET("resource_prismatic-socket"),

    ROCKET_ARRAY_MODULE_LOW_ACCURACY("module_ram-la"),
    ROCKET_ECO_10("ammunition_rocketlauncher_eco-10"),
    ROCKET_HSTRM_01("ammunition_rocketlauncher_hstrm-01"),
    ROCKET_LAUNCHER_HST_2("equipment_weapon_rocketlauncher_hst-2"),
    ROCKET_PLT_2021("ammunition_rocket_plt-2021"),
    ROCKET_PLT_2026("ammunition_rocket_plt-2026"),
    ROCKET_PLT_3030("ammunition_rocket_plt-3030"),
    ROCKET_R_310("ammunition_rocket_r-310"),
    ROCKET_SAR_02("ammunition_rocketlauncher_sar-02"),
    ROCKET_UBR_100("ammunition_rocketlauncher_ubr-100"),
    ROCKET_BDR_1211("ammunition_rocket_bdr-1211"),
    ROCKET_BDR_1212("ammunition_rocketlauncher_bdr1212"),

    SHIELD_GENERATOR_SG3N_A03("equipment_generator_shield_sg3n-a03"),
    SHIELD_GENERATOR_SG3N_B01("equipment_generator_shield_sg3n-b01"),
    SHIELD_GENERATOR_SG3N_B02("equipment_generator_shield_sg3n-b02"),
    SHIELD_GENERATOR_SG3N_B03("equipment_generator_shield_sg3n-b03"),
    SHIELD_GENERATOR_FS_03("equipment_generator_shield_fs-03"),
    SPEED_GENERATOR_G3N_6900("equipment_generator_speed_g3n-6900"),
    SPEED_GENERATOR_G3N_7900("equipment_generator_speed_g3n-7900"),

    SHIP_AEGIS("ship_aegis"),
    SHIP_CITADEL_ELITE("ship_c-elite"),
    SHIP_GOLIATH("ship_goliath"),
    SHIP_VENGEANCE_AVENGER("ship_v-avenger"),
    SHIP_GOLIATH_EXALTED("ship_g-exalted"),
    SHIP_VENGEANCE_ADEPT("ship_v-adept"),
    SHIP_SOLACE("ship_solace"),
    SHIP_GOLIATH_ENFORCER("ship_g-enforcer"),
    SHIP_VENGEANCE_CORSAIR("ship_v-corsair"),
    SHIP_VENGEANCE_LIGHTNING("ship_v-lightning"),
    SHIP_VENOM("ship_venom"),
    SHIP_GOLIATH_BASTION("ship_g-bastion"),
    SHIP_VENGEANCE_REVENGE("ship_v-revenge"),
    SHIP_GOLIATH_VETERAN("ship_g-veteran"),
    SHIP_CITADEL("ship_citadel"),
    SHIP_VENGEANCE("ship_vengeance"),
    SHIP_AEGIS_ELITE("ship_a-elite"),
    SHIP_SPECTRUM("ship_spectrum"),
    SHIP_GOLIATH_DESIGN_CRIMSON("ship_goliath_design_crimson"),
    SHIP_GOLIATH_DESIGN_AMBER("ship_goliath_design_amber"),
    SHIP_GOLIATH_DESIGN_JADE("ship_goliath_design_jade"),
    SHIP_GOLIATH_DESIGN_SAPHIRE("ship_goliath_design_sapphire"),
    SHIP_GOLIATH_PLUS("ship_goliath-plus"),

    SHIP_UPGRADE_HP_X2("equipment_shipupgrade_hp-x2"),
    SHIP_UPGRADE_HP_XA01("equipment_shipupgrade_hp-xa01"),
    SHIP_UPGRADE_HP_XT10("equipment_shipupgrade_hp-xt10"),
    SHIP_UPGRADE_SHD_BACH01("equipment_shipupgrade_shd-bach01"),
    SHIP_UPGRADE_SHD_X2("equipment_shipupgrade_shd-x2"),
    SHIP_UPGRADE_SHD_XA01("equipment_shipupgrade_shd-xa01"),
    SHIP_UPGRADE_SHD_XV02("equipment_shipupgrade_shd-xv02"),
    SHIP_UPGRADE_SPC_DIM01("equipment_shipupgrade_spc-dim01"),
    SHIP_UPGRADE_SPC_SPD01("equipment_shipupgrade_spc-spd01"),
    SHIP_UPGRADE_SPC_X2("equipment_shipupgrade_spc-x2"),
    SHIP_UPGRADE_SPC_XU01("equipment_shipupgrade_spc-xu01"),
    SHIP_UPGRADE_DMG_MTCH01("equipment_shipupgrade_dmg-mtch01"),
    SHIP_UPGRADE_DMG_NPC01("equipment_shipupgrade_dmg-npc01"),
    SHIP_UPGRADE_DMG_X2("equipment_shipupgrade_dmg-x2"),
    SHIP_UPGRADE_DMG_XA01("equipment_shipupgrade_dmg-xa01"),
    SHIP_UPGRADE_DMG_XT10("equipment_shipupgrade_dmg-xt10"),
    SHIP_UPGRADE_DMG_XU01("equipment_shipupgrade_dmg-xu01"),
    SHIP_UPGRADE_DMG_XV02("equipment_shipupgrade_dmg-xv02"),
    SHIP_UPGRADE_DMG_ZPVE("equipment_shipupgrade_dmg-zpve"),

    SPECIAL_AMMO_EMP_01("ammunition_specialammo_emp-01"),
    SPECIAL_AMMO_PLD_8("ammunition_specialammo_pld-8"),
    SPECIAL_AMMO_WIZARD("ammunition_specialammo_wiz-x"),
    SPECIAL_AMMO_ALIEN_CRY_EMOTE("ammunition_specialammo_emote_alien-cry"),
    SPECIAL_AMMO_ALIEN_HORROR_EMOTE("ammunition_specialammo_emote_alien-horror"),
    SPECIAL_AMMO_ALIEN_SORRY_EMOTE("ammunition_specialammo_emote_alien-sorry"),
    SPECIAL_AMMO_BUNNY_CONFUSED_EMOTE("ammunition_specialammo_emote_bunny-confused"),
    SPECIAL_AMMO_BUNNY_COOL_EMOTE("ammunition_specialammo_emote_bunny-cool"),
    SPECIAL_AMMO_BUNNY_COOL_SAD("ammunition_specialammo_emote_bunny-sad"),
    SPECIAL_AMMO_BUNNY_COOL_SLEEPY("ammunition_specialammo_emote_bunny-sleepy"),
    SPECIAL_AMMO_DCR_250("ammunition_specialammo_dcr-250"),
    SPECIAL_AMMO_EASTER_EGGS_SPRAY("ammunition_specialammo_spray_easter-eggs"),
    SPECIAL_AMMO_EGGLE_SPRAY("ammunition_specialammo_spray_eggle"),
    SPECIAL_AMMO_EGGTOPIA_SPRAY("ammunition_specialammo_spray_eggtopia"),
    SPECIAL_AMMO_RIC3("ammunition_specialammo_r-ic3"),
    SPECIAL_AMMO_SKULL_SPRAY("ammunition_specialammo_spray_skull"),
    SPECIAL_AMMO_SPACE_BUNNY_SPRAY("ammunition_specialammo_spray_space-bunny"),
    SPECIAL_AMMO_SR_5("ammunition_specialammo_sr-5");

    private final String localizationID;
    private LocalizationID(String id) {
        this.localizationID = id;
    }

    public String getLocalizationID() {
        return this.localizationID;
    }
}
